### ISSUE TITLE
Add a setting to ignore tutorials

### ISSUE THREAD

**Issue by HeavyWolfPL** [kingsplayground/Ultimate-AFK#6]
Title

**Comment by thomasjosif** [comment]
Why would this be required? If you want tutorial's ignored because they are admin can't you just use the permission?

**Comment by HeavyWolfPL** [comment]
But if admin goes afk he could stand the entire round somewhere in the facility preventing the round to end.

**Comment by thomasjosif** [comment]
This sounds more like a niche issue rather than something that would benefit more than one user. If you would like to disable AFK checking just use the AFK ignore permission. If you can't trust your admins to not go afk in the first place why would you want it disabled in Tutorial? They could just go AFK in Tutorial and the same issue applies. 

Closing this as I don't have plans to implement it. Sorry.
